### ISSUE TITLE
Localizing problem

### ISSUE THREAD

**Issue by meSutPiskin** [oskopek/javaanpr#23]
Hi all.
I have a problem for localizing problem. I want to read Turkey plate but I getting an error not read. why could it be. Which should I use syntax.

my xml syntax

```
<type name="turkey">
   <char content="0123456789"/>
   <char content="0123456789"/>
   <char content="abcdefghijklmno0pqrstuvwxyz"/>
   <char content="abcdefghijklmno0pqrstuvwxyz"/>
   <char content="0123456789"/>
   <char content="0123456789"/>
   <char content="0123456789"/>
 </type>
```

Turkey plates
[http://s2.postimg.org/yk22frxnt/Ph_Peugeot_Birmilyon_Plaka_04.jpg](http://s2.postimg.org/yk22frxnt/Ph_Peugeot_Birmilyon_Plaka_04.jpg)

and my result is failed
[http://s12.postimg.org/vll3ddiel/image.png](http://s12.postimg.org/vll3ddiel/image.png)

Thank you so much for help.

**Comment by oskopek** [comment]
Hi,

your syntax looks good.

Sometimes, JavaANPR doesn't detect the plate correctly, for a number of reasons.
For some suggestions, see issue #22. I'd suggest to run the report generator, and identify the problem there.

**Comment by meSutPiskin** [comment]
@oskopek Thank you su much for answer.

**Comment by oskopek** [comment]
Closing, as a duplicate of #22.
