### ISSUE TITLE
Screenshot in readme stopped working

### ISSUE THREAD

**Issue by oskopek** [oskopek/javaanpr#24]
Add a new one and embed it in the readme.

**Comment by Arinerron** [comment]
Several months later:

...

Nothing...

------

![screenshot from 2016-06-16 21 37 26](https://cloud.githubusercontent.com/assets/3926753/16140907/a247bc10-340a-11e6-87f4-f00840fc1650.png)

**Comment by oskopek** [comment]
Hi Arinerron,

I maintain JavaANPR in my free time, which -- as you pointed out -- I don't have very much of.
Sorry for disappointing you, I'll do my best to fix this over the weekend.

Although, do note, that this project is open-source. You're very welcome to fix the issue (it's quite easy, try it!) and open a pull request :)

**Comment by Arinerron** [comment]
@oskopek Thanks! I am a student developer (in middle school?), so I have all day to work on stuff. I just wanted to see a screenshot so that I don't get it and integrate it and then realize it doesn't work for my needs.

**Comment by oskopek** [comment]
@Arinerron for easy integration, see https://github.com/oskopek/javaanpr/blob/master/src/test/java/net/sf/javaanpr/test/RecognitionIT.java#L48
