### ISSUE TITLE
black plate

### ISSUE THREAD

**Issue by fgaudenzi** [oskopek/javaanpr#25]
hello,
How is it possible to make to it works with plates that has black or red background?
I'm facing with Singapore plates that are negative than ours in europe.

**Comment by oskopek** [comment]
Hi.. wow, never even heard of that nor tried it. Have you tried running JavaANPR on them? Also, take a look at enabling report generation, to see where it failed (if it did). See #22 for details

**Comment by oskopek** [comment]
Take a look at https://github.com/oskopek/javaanpr/blob/master/docs/howto-use-reports.adoc. Closing as wontfix, feel free to reopen in case you have any questions.
