### ISSUE TITLE
Not reading full plate

### ISSUE THREAD

**Issue by EoANishant** [oskopek/javaanpr#27]
Hi,
I am trying to use javaanpr for Indian number plates. I am using this as an input file 
![test8_m2](https://cloud.githubusercontent.com/assets/8317620/17293258/deb386a4-580c-11e6-83df-b350acbd38b5.jpg)

The report generation here :

![test8_m2report](https://cloud.githubusercontent.com/assets/8317620/17293304/22adfd94-580d-11e6-8651-534c0eb7117b.jpg)

Can you tell me what thing i am going wrong. I am getting this issue when there is a space in the number plate.

Here is what i am using:

```xml
<?xml version="1.0" encoding="iso-8859-2"?>

structure>


type name="India">
char content="abcdefghijklmno0pqrstuvwxyz"/>
char content="abcdefghijklmno0pqrstuvwxyz"/>
char content=" "/>
char content="o0123456789"/>
char content="o0123456789"/>
char content=" "/>
char content="abcdefghijklmno0pqrstuvwxyz"/>
char content="abcdefghijklmno0pqrstuvwxyz"/>
char content=" "/>
char content="o0123456789"/>
char content="o0123456789"/>
char content="o0123456789"/>
char content="o0123456789"/>
/type>

　
　
　
</structure>
```

**Comment by EoANishant** [comment]
i adjusted the size of image , and now i am getting this :

![testm2_report](https://cloud.githubusercontent.com/assets/8317620/17293885/b8537e2a-5810-11e6-9927-5969882dd2aa.jpg)

Why is it ommitting the first 2 ?

I changed my syntax file too .. 

?xml version="1.0" encoding="iso-8859-2"?>

structure>


type name="India">
char content="abcdefghijklmno0pqrstuvwxyz"/>
char content="abcdefghijklmno0pqrstuvwxyz"/>
char content="o0123456789"/>
char content="o0123456789"/>
char content="abcdefghijklmno0pqrstuvwxyz"/>
char content="abcdefghijklmno0pqrstuvwxyz"/>
char content="o0123456789"/>
char content="o0123456789"/>
char content="o0123456789"/>
char content="o0123456789"/>
/type>

　
　
　
/structure>

**Comment by oskopek** [comment]
You seem to have done everything correctly as far as I can tell (if you only forgot to paste the first two characters of every line in your config and have them in your file).

One thing that occurred to me now: are you sure you are actually *using* the correct syntax file? 

JavaANPR seems to be looking for 10 characters, where you have configured 11 in your syntax file type. Make sure you remove the other types from the syntax file (or create a new one and point the config at it).

**Comment by EoANishant** [comment]
i am not able to understand when is this syntax file actually getting used. I removed all the contents of the syntax file in target folder and still it was giving me results .

**Comment by oskopek** [comment]
In the `String parse(RecognizedPlate recognizedPlate, int syntaxAnalysisMode)` method of `Parser`. You might want to try "1" as `syntax_analysis_mode`

**Comment by EoANishant** [comment]
I will do that. Can u please look at my above comment . Also are u using JFK 1.6 for development environment . I am getting some errors in eclipse setup like generic types which I can post here but that will mix two topics. I will open a separate issue for that

**Comment by EoANishant** [comment]
I believe you are saying this 
    

    
    

> <entry key="intelligence_syntaxanalysis">1</entry>

    
    <entry key="intelligence_syntaxDescriptionFile">syntax/syntax.xml</entry>

    

I am using the value as 1 .

**Comment by EoANishant** [comment]
Hey , i observed one thing in letters which are not getting shown up  !! I will just look up where this value is getting calculated!
![neutest1](https://cloud.githubusercontent.com/assets/8317620/17310243/c4af91cc-5860-11e6-935f-4e827e3e83d3.jpg)

**Comment by oskopek** [comment]
You might want to open another issue about your dev environemnt not working.

I'll get to your questions later, during the weekend probably :)

**Comment by EoANishant** [comment]
The development stuff is sorted out. I actually have to show this in my college day after tomorrow.  Don't what u to test it out but just two questions 

1.what is the use of syntax.xml and when is it used
2.the pattern that I made for above pic is right ? What to do when u encounter a space in the plate. Do we specify another char entry for that ?

**Comment by EoANishant** [comment]
Can u please just answer these questions ? I need it urgently

. I actually have to show this in my college day after tomorrow.  Don't
what u to test it out but just two questions

1.what is the use of syntax.xml and when is it used
2.the pattern that I made for above pic is right ? What to do when u
encounter a space in the plate. Do we specify another char entry for that ?

**Comment by oskopek** [comment]
1. Already told you, take a look at the `String parse(RecognizedPlate recognizedPlate, int syntaxAnalysisMode)` method of the `Parser`. As far as I can tell, your syntax file is correct. Verify that you're actually using the correct syntax file in the config file.

2. Consult the original documentation http://javaanpr.sourceforge.net/anpr.pdf (chapters 5 and 6 might be useful), and experiment around :)

Pull Requests are always welcome, either for documentation enhancement or code enhancements.

**Comment by oskopek** [comment]
Also, I tried the image you supplied, and it worked just fine with the correct syntax:

![javaanpr_plate_example](https://cloud.githubusercontent.com/assets/1811716/17344410/3c2d63ea-5902-11e6-9aae-251017c68ec4.png)

**Comment by EoANishant** [comment]
"correct syntax file in the config file."
I am using the syntax file i.e generated in the target folder after a full
build.
In src folder : P:\code_workspace\javaanpr\src\main\resources\syntax   This
is the one which gets copied to the the target folder. I am modifyng the
one in the target as the jar that i run will use this syntax file in target
folder.

But syntax file in config file ? I did modified the config file just to see
if it takes the image and gives the result .

**Comment by EoANishant** [comment]
And one thing , not to mention, you really have done a great work sir. Its
a pleasure to be learning from you

**Comment by oskopek** [comment]
Config file = `src/main/resources/config.xml`, see this part: `<entry key="intelligence_syntaxDescriptionFile">syntax/syntax.xml</entry>`

**Comment by EoANishant** [comment]
I debugged this to find where this syntax.xml file is getting loaded.

Added some sysouts

21:14:43.679 [main] DEBUG n.s.j.neuralnetwork.NeuralNetwork - Created
neural input 19 with weight -3.617587524230886.
File initialised config.xml
syntax file present in syntax\syntax.xml
Stream with syntax file initialised
Reading the syntax file and loading the xml nodes
Head of document #document
Structure node read structure has value null :



 has childs [structure: null]
structureNode.getChildNodes() refers to a node 3
Starting to read the type node
Starting to read the type node
type node read is type:

 has child nodes [type: null]
Reading plateform for the typenode India


Here u can see, its loading India ! which means i am modifying the right
file. I am just checking when does an image gets displayed and when does it
not and what relation does it have with this syntax.xml contexts which is
loaded in plateform .

**Comment by oskopek** [comment]
I already told you twice, check out the `Parser`. Specifically, `String parse(RecognizedPlate recognizedPlate, int syntaxAnalysisMode)`.

**Comment by EoANishant** [comment]
Yes , i am just looking at that only now.

**Comment by EoANishant** [comment]
Ohk , i got this . When ur control comes in parser method. it checks for if
(syntaxAnalysisMode == 1) . If this is 1, , it will go and compare the form
elements in the for loop : for (int i = 0; i <= (length - form.length());
i++) { // moving the form on the plate

I got it till here . Now , if i have specified the correct syntax.xml and
all , why i am getting weird results for Number plates which have the same
format.
There can be one reason :
1.The image is blurred ( " which is ok ")
But what i am observing is , if the number plate has a space like below

i am getting weird results.

**Comment by EoANishant** [comment]
Finally its done . Thank you so much . After submitting the project , i
will fork the repo and will work on this again to read 2 line number
plates.

**Comment by oskopek** [comment]
If you feel this issue is resolved, please close it :) Thanks for using JavaANPR!

**Comment by EoANishant** [comment]
Yes I will.
