### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by rebelangelo** [oskopek/javaanpr#65]
Hi,

When I try to recognize plate on gui it throws this exception.

Exception in thread "Thread-6" java.lang.NullPointerException
	at net.sf.javaanpr.gui.windows.FrameMain.access$700(FrameMain.java:36)
	at net.sf.javaanpr.gui.windows.FrameMain$RecognizeThread.run(FrameMain.java:288)

at line 288 parentFrame is null

Is there any problem with my build? I tried to run javaanpr from command line and throws same thing

Thanks

**Comment by oskopek** [comment]
Hi @rebelangelo,

Thanks for reporting the bug! This should be now fixed in latest master (after commit c33a0f94e00683df5545844e99dcb5d1e8670997).

Could you please get the latest version and verify?

Thanks!

**Comment by oskopek** [comment]
Assuming this is fixed. If not, please reopen.
