### ISSUE TITLE
How do I get Finnish license plates working

### ISSUE THREAD

**Issue by mronnlun** [oskopek/javaanpr#69]
I have a bunch of pictures of Finnish license plates here [https://www.dropbox.com/sh/17mdp2ki98oh9v3/AADIXXSaT4uS2gq8dbYpMJnoa?dl=0](https://www.dropbox.com/sh/17mdp2ki98oh9v3/AADIXXSaT4uS2gq8dbYpMJnoa?dl=0) but they won't be recognized. I've tried the report feature but can't really figure out what the problem is.

Are the images the wrong size? The license plates here are ABC-123, so do I need to specify the dash in the syntax file and create an dash alphbet picture?

**Comment by oskopek** [comment]
Yes, changing the syntax file should help. Would you mind doing that and uploading a zip containing the report folder? Thanks for using JavaANPR!

**Comment by oskopek** [comment]
Closing as inactive.
