### ISSUE TITLE
can u make this sourceforge.net code to work for indian license plate

### ISSUE THREAD

**Issue by ShreyasMurali** [oskopek/javaanpr#70]
hey,
i have been trying to implement this for indian license plate but for some reason it isnt working for indian plates. i only detects partial plate 
PLEASE HELP

**Comment by oskopek** [comment]
Take a look at https://github.com/oskopek/javaanpr/blob/master/docs/howto-use-reports.adoc

**Comment by oskopek** [comment]
Closing as inactive.
