### ISSUE TITLE
add new character

### ISSUE THREAD

**Issue by parsibox** [oskopek/javaanpr#71]
hi
how can i add new character ?
for example i want add this character
ب
please help me
i need this

**Comment by oskopek** [comment]
Sorry, I do not know how to do that exactly, haven't really tried to use the training feature. Take a look at the classes around `NeuralNetwork`.

**Comment by parsibox** [comment]
no i do not see this class
can you write an example how to use NeuralNetwork class?

**Comment by oskopek** [comment]
Believe me, it is there: https://github.com/oskopek/javaanpr/blob/master/src/main/java/net/sf/javaanpr/neuralnetwork/NeuralNetwork.java

Also, take a look at `learnAlphabet`: https://github.com/oskopek/javaanpr/blob/master/src/main/java/net/sf/javaanpr/jar/Main.java#L120

**Comment by parsibox** [comment]
thanks
i will try this method as soon as posible

**Comment by oskopek** [comment]
Closing as inactive.
