### ISSUE TITLE
Chinese plate recognition.

### ISSUE THREAD

**Issue by myVictor** [oskopek/javaanpr#73]
Can it recognize Chinese characters?

**Comment by oskopek** [comment]
It may be possible, but I think it will be tough to set up.

Take a look at:
https://github.com/oskopek/javaanpr/blob/master/src/main/java/net/sf/javaanpr/neuralnetwork/NeuralNetwork.java

and learnAlphabet: https://github.com/oskopek/javaanpr/blob/master/src/main/java/net/sf/javaanpr/jar/Main.java#L120
