### ISSUE TITLE
"Plugin execution not covered..."

### ISSUE THREAD

**Issue by martijintro** [oskopek/javaanpr#85]
1. git clone....
2. import in eclipse (j2ee version), newest version freshly downloaded

Error:  `Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (execution: validate, phase: validate)	pom.xml	/javaanpr	line 171	Maven Project Build Lifecycle Mapping Problem`

**Comment by martijintro** [comment]
to add `<pluginManagement> ... </pluginManagement` seems to solve (or just hide?) the problem -> https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

**Comment by oskopek** [comment]
That indeed only hides the problem. On the other hand, that plugin is non-essential, feel free to submit a pull request with your changes :)

**Comment by martijintro** [comment]
Thx! :-)
